import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const oSans = localFont({
  src: [
    { path: "../../public/fonts/OSans-Light.ttf",   weight: "300", style: "normal" },
    { path: "../../public/fonts/OSans-Regular.ttf", weight: "400", style: "normal" },
    { path: "../../public/fonts/OSans-Medium.ttf",  weight: "500", style: "normal" },
    { path: "../../public/fonts/OSans-Bold.ttf",    weight: "600", style: "normal" },
    { path: "../../public/fonts/OSans-Bold.ttf",    weight: "700", style: "normal" },
    { path: "../../public/fonts/OSans-Bold.ttf",    weight: "800", style: "normal" },
    { path: "../../public/fonts/OSans-Bold.ttf",    weight: "900", style: "normal" },
  ],
  variable: "--font-osans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Brand Edge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`h-full antialiased ${oSans.variable} ${oSans.className}`}>
      <body className={`min-h-full flex flex-col ${oSans.className}`}>{children}</body>
    </html>
  );
}
