/* ── All project case studies ───────────────────────── */
export const ALL_PROJECTS = [
  {
    slug: "jesup-wireless",
    title: "Jesup Wireless — Digital Store",
    client: "Jesup Wireless",
    category: "E-Commerce",
    year: "2024",
    duration: "3 Weeks",
    team: "1 Designer · 2 Developers · 1 Strategist",
    deliverables: "E-Commerce Website, Brand Identity, UI/UX",
    image: "/projects/jesup.png",
    liveUrl: "https://shop.jesupwireless.com",
    tags: ["E-Commerce", "Branding", "UI/UX"],
    overview: "Jesup Wireless, a US-based wireless retailer, came to us needing a complete digital storefront that matched the quality of their products. Their previous online presence was basic, slow, and failing to convert visitors. We designed and built a full e-commerce experience — fast, mobile-first, and built to sell.",
    challenge: "The wireless accessories market is crowded and highly price-competitive. The challenge was building a store that felt premium and trustworthy enough to stand out, while keeping the buying journey frictionless from product discovery to checkout.",
    phases: [
      { name: "Discovery & Strategy",    duration: "3 days",  desc: "Competitor audit of top US wireless retailers, customer journey mapping, and conversion funnel planning to prioritise the right features." },
      { name: "Brand & Visual Design",   duration: "5 days",  desc: "Logo refinement, colour system, typography, and a full UI kit designed for e-commerce — product cards, CTAs, badges, and checkout flows." },
      { name: "Development",             duration: "10 days", desc: "Full e-commerce build — product catalogue, cart, checkout, mobile-responsive layouts, and performance optimisation for fast load times." },
      { name: "QA & Launch",             duration: "3 days",  desc: "Cross-device testing, payment flow QA, page speed audit, and a smooth go-live with zero downtime." },
    ],
    results: [
      { val: "3×",  label: "Faster Page Load" },
      { val: "40%", label: "Higher Conversion Rate" },
      { val: "98",  label: "Mobile Lighthouse Score" },
      { val: "3wk", label: "Design to Live" },
    ],
    outcome: "Jesup Wireless launched their new store to immediate positive feedback from customers. The streamlined checkout and mobile-first design significantly improved the buying experience, and the brand identity gave the business a professional edge it was previously missing.",
  },
  {
    slug: "nanya-cnc",
    title: "NANYA CNC — Web Presence",
    client: "NANYA CNC",
    category: "Web Design",
    year: "2024",
    duration: "2 Weeks",
    team: "1 Designer · 1 Developer",
    deliverables: "Corporate Website, UI/UX, Copywriting",
    image: "/projects/nanya.png",
    liveUrl: "https://nye-cnc.com",
    tags: ["Web Design", "UI/UX", "Development"],
    overview: "NANYA CNC is a precision CNC manufacturing company that needed a website as precise as their machines. Their old web presence didn't communicate the scale or quality of their capabilities. We built a clean, professional corporate website that speaks directly to B2B buyers and industry partners.",
    challenge: "CNC manufacturing is a highly technical field. The website needed to be authoritative enough for engineers and procurement managers, while remaining accessible to non-technical decision-makers. Every design choice had to communicate precision and reliability.",
    phases: [
      { name: "Discovery & Positioning",   duration: "2 days",  desc: "Stakeholder interviews, target audience mapping, and competitive analysis of leading CNC manufacturers worldwide." },
      { name: "UX & Information Design",   duration: "3 days",  desc: "Sitemap and wireframes built around B2B inquiry flow — services first, capabilities second, contact always within reach." },
      { name: "Visual Design",             duration: "5 days",  desc: "Clean industrial aesthetic — dark tones, precision typography, technical imagery, and a design language built on trust and capability." },
      { name: "Development & Launch",      duration: "4 days",  desc: "Fully responsive build, enquiry form integration, SEO foundation, and cross-browser QA before a clean handoff." },
    ],
    results: [
      { val: "2×",  label: "More B2B Inquiries" },
      { val: "55%", label: "Lower Bounce Rate" },
      { val: "14d", label: "Concept to Launch" },
      { val: "A+",  label: "Client Satisfaction" },
    ],
    outcome: "NANYA CNC's new website immediately elevated the business in the eyes of potential partners. Within the first month, inbound B2B inquiries doubled — and the client reported that new leads were arriving better-informed and more decision-ready than ever before.",
  },
  {
    slug: "action-plus-tax",
    title: "Action Plus Tax — Brand & Web",
    client: "Action Plus Tax",
    category: "Branding",
    year: "2025",
    duration: "2 Weeks",
    team: "1 Designer · 1 Developer · 1 Strategist",
    deliverables: "Brand Identity, Website, Visual Guidelines",
    image: "/projects/action.png",
    liveUrl: "https://actionplustax.com",
    tags: ["Branding", "Web Design", "Identity"],
    overview: "Action Plus Tax is a growing tax consultancy that needed a brand identity and website to match its ambitions. In the financial services space, trust is everything — and their existing look wasn't earning it. We rebuilt their brand from the ground up and launched a website designed to convert first-time visitors into long-term clients.",
    challenge: "Tax consultancies often look generic and interchangeable. The challenge was creating an identity that felt authoritative and trustworthy without being cold or corporate — a brand that real people and small businesses would actually want to work with.",
    phases: [
      { name: "Brand Strategy",          duration: "2 days",  desc: "Defined the brand positioning, target audience personas, tone of voice, and a set of brand values that would drive every design decision." },
      { name: "Identity Design",         duration: "4 days",  desc: "Logo design across 3 concepts, selected colour palette (professional navy and gold), typography system, and brand guidelines document." },
      { name: "Website Design",          duration: "4 days",  desc: "Conversion-focused layout — services clearly presented, trust signals throughout, and a prominent CTA driving free consultation bookings." },
      { name: "Development & Launch",    duration: "4 days",  desc: "Fully responsive website build, contact form integration, Google Maps embed, SEO basics, and a smooth production launch." },
    ],
    results: [
      { val: "3×",  label: "More Consultation Bookings" },
      { val: "60%", label: "Lower Bounce Rate" },
      { val: "14d", label: "Strategy to Launch" },
      { val: "A+",  label: "Client Satisfaction" },
    ],
    outcome: "Action Plus Tax launched with a brand that finally matched the quality of their service. Consultation bookings tripled in the first month, and the client reported that new leads were arriving pre-sold on the brand — no longer needing to be convinced of credibility before the conversation even started.",
  },
  {
    slug: "taeri",
    title: "TAERI — Elderly Health App",
    client: "TAERI",
    category: "App Dev",
    year: "2025",
    duration: "6 Weeks",
    team: "1 Designer · 2 Developers · 1 Strategist",
    deliverables: "Mobile App UI, Task Flow System, Health Dashboard",
    image: "/projects/taeri.png",
    liveUrl: "",
    tags: ["App Dev", "UI/UX", "Health"],
    overview: "TAERI is a health companion application built specifically for senior citizens — a demographic that is often underserved by modern technology. The app was designed around one core belief: that staying healthy in old age should feel empowering, not complicated. Users begin by selecting the type of activity they want to perform, then the app gently guides them through personalised parameters — how much time they have, the physical angle or posture involved, and the difficulty level that suits their current ability. Everything is designed with large text, simple navigation, and calm visuals to ensure comfort for elderly users.",
    challenge: "Designing for senior citizens presents a unique set of challenges. Most apps assume a baseline of tech-literacy that older users may not have. Our challenge was to create an experience that felt warm and approachable — not clinical — while still being detailed enough to be genuinely useful for health management. Every tap, every screen, and every word of copy had to be considered through the lens of someone who may be encountering a smartphone app for the very first time.",
    phases: [
      { name: "Research & User Empathy",   duration: "1 week",  desc: "In-depth research into elderly UX patterns, accessibility standards, and common health concerns for senior citizens. Interviews and journey mapping focused on simplicity and trust." },
      { name: "Task Flow Design",           duration: "1 week",  desc: "Designed the core task selection system — users pick an activity (e.g. walking, stretching, physiotherapy), then set time duration, body angle/posture, and difficulty level on a simple slider scale." },
      { name: "UI Design & Accessibility", duration: "2 weeks", desc: "High-contrast visuals, large tap targets, clear iconography, and calm colour palette. Every screen was tested for readability and ease of use with minimal cognitive load." },
      { name: "Development & Testing",     duration: "2 weeks", desc: "Full mobile app build with smooth onboarding flow, task tracking, daily progress summaries, and caregiver notification feature. Tested across multiple device sizes." },
    ],
    results: [
      { val: "95%",  label: "Ease of Use Rating" },
      { val: "3 taps", label: "Avg. to Start a Task" },
      { val: "A+",   label: "Accessibility Score" },
      { val: "6wks", label: "Concept to Delivery" },
    ],
    outcome: "TAERI delivered a product that genuinely resonated with its target audience — senior citizens who often feel left behind by technology. The simple task-selection flow, combined with thoughtful accessibility design, made it easy for elderly users to engage with their health routines daily. The client praised the team's ability to translate a complex health concept into something that felt effortless and human.",
  },
];

export type Project = (typeof ALL_PROJECTS)[number];
